version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


# services:
#  web:
#    build: .
#    ports:
#      - "8000:5000"
#  rabbitmq:
#    image: "rabbitmq:3.9.13-management"
#    environment:
#      - RABBITMQ_DEFAULT_USER=liel
#      - RABBITMQ_DEFAULT_PASS=1234