# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.models.base_model_ import Model
from app import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, blog_name: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param blog_name: The blog_name of this InlineResponse200.  # noqa: E501
        :type blog_name: str
        """
        self.swagger_types = {
            'blog_name': str
        }

        self.attribute_map = {
            'blog_name': 'blog_name'
        }
        self._blog_name = blog_name

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blog_name(self) -> str:
        """Gets the blog_name of this InlineResponse200.


        :return: The blog_name of this InlineResponse200.
        :rtype: str
        """
        return self._blog_name

    @blog_name.setter
    def blog_name(self, blog_name: str):
        """Sets the blog_name of this InlineResponse200.


        :param blog_name: The blog_name of this InlineResponse200.
        :type blog_name: str
        """

        self._blog_name = blog_name
